#!/bin/bash

build_dir="$PWD/build"
services_dir_prefix="src/server/services"

function build_image() {
	docker build -t "$1" -f "$build_dir/$1/Dockerfile.release" "$build_dir/$1"
}

function build_identity_api_image() {
	local api_name="api_identity"
	build_image $api_name
}

function build_postsys_api_image() {
	local api_name="api_postsys"
	build_image $api_name
}

function build_postsys_comment_api_image() {
	local api_name="api_postsys_comment"
	build_image $api_name
}

build_identity_api_image \
	&& build_postsys_api_image \
	&& build_postsys_comment_api_image \ 

docker image prune