#!/bin/bash

build_dir="$PWD/build"
services_dir_prefix="src/server/services"

identity_db="ncc.identity"
postsys_db="ncc.postsys"

function build_identity_api() {
	local api_name="api_identity"
	local csproj="$services_dir_prefix/identity/api/Ncc.China.Services.Identity.Api.csproj"
	
	echo "[1/3] Start build $api_name ..."
	dotnet publish -c Release -o "$build_dir/$api_name" "$csproj" \
		&& echo "[1/3] build finished!"
}

function build_postsys_api() {
	local api_name="api_postsys"
	local csproj="$services_dir_prefix/postsys/api/Ncc.China.Services.Postsys.Api.csproj"
	
	echo "[2/3] Start build $api_name ..."
	dotnet publish -c Release -o "$build_dir/$api_name" "$csproj" \
		&& echo "[2/3] build finished!"
}

function build_postsys_comment_api() {
	local api_name="api_postsys_comment"
	local proj_dir="$services_dir_prefix/postsys_comment"
	
	echo "[3/3] Start build $api_name ..."

	if [ ! -d "build/$api_name" ]; then
		mkdir -p "build/$api_name"
	fi

	# copy all files and dir exinclude `node_modules` dir
	ls $proj_dir \
		| grep -v "node_modules" \
		| xargs -i cp -r $proj_dir/{} $build_dir/$api_name \
		&& echo "[3/3] build finished!"
}

build_identity_api \
	&& build_postsys_api \
	&& build_postsys_comment_api
