#!/bin/bash

pwd_dir=$(pwd)
build_dir="$pwd_dir/build"
services_dir_prefix="src/server/services"

identity_db="ncc.identity"
postsys_db="ncc.postsys"

function run_identity_api() {
	local api_name="api_identity"
	local csproj="$services_dir_prefix/identity/api/Ncc.China.Services.Identity.Api.csproj"
	dotnet publish -c Release -o "$build_dir/$api_name" "$csproj"
        docker build -t "$api_name" -f "$build_dir/$api_name/Dockerfile.release" "$build_dir/$api_name"
        #docker run --name "test_$api_name" --rm -p 5001:80 -d --link "$identity_db" "$api_name"
}

function run_postsys_api() {
	local api_name="api_postsys"
	local csproj="$services_dir_prefix/postsys/api/Ncc.China.Services.Postsys.Api.csproj"
	dotnet publish -c Release -o "$build_dir/$api_name" "$csproj"
        docker build -t "$api_name" -f "$build_dir/$api_name/Dockerfile.release" "$build_dir/$api_name"
        #docker run --name "test_$api_name" --rm -p 5002:80 -d --link "$postsys_db" "$api_name"
}

function run_postsys_comment_api() {
	# TODO
}

# mkdir "$build_dir"

# run_identity_api && run_postsys_api