// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ncc.China.Services.Identity.Data;

namespace Ncc.China.Services.Identity.Api.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20181101134905_init_db")]
    partial class init_db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ncc.China.Services.Identity.Data.LoginUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("char(32)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("varchar(100)");

                    b.Property<sbyte>("IsAdmin")
                        .HasColumnName("is_admin")
                        .HasColumnType("tinyint(2)");

                    b.Property<sbyte>("IsDeleted")
                        .HasColumnName("is_deleted")
                        .HasColumnType("tinyint(2)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnName("salt")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("username")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UtcCreated")
                        .HasColumnName("utc_created")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UtcUpdated")
                        .HasColumnName("utc_updated")
                        .HasColumnType("datetime ");

                    b.HasKey("Id")
                        .HasName("pk_id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Ncc.China.Services.Identity.Data.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnName("avatar_url")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnName("bio")
                        .HasColumnType("varchar(200)");

                    b.Property<sbyte>("Gender")
                        .HasColumnName("gender")
                        .HasColumnType("tinyint(3)");

                    b.Property<string>("Nickname")
                        .HasColumnName("nickname")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnName("user_id")
                        .HasColumnType("char(32)");

                    b.Property<DateTime>("UtcCreated")
                        .HasColumnName("utc_created")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UtcUpdated")
                        .HasColumnName("utc_updated")
                        .HasColumnType("datetime ");

                    b.HasKey("Id")
                        .HasName("pk_id");

                    b.ToTable("user_profile");
                });
#pragma warning restore 612, 618
        }
    }
}
